#! /usr/bin/env python3
# -----------------------------------------------------------------------------
# Copyright (C) 2026 Iliyas Jorio.
# This file is part of GitFourchette, distributed under the GNU GPL v3.
# For full terms, see the included LICENSE file.
# -----------------------------------------------------------------------------

import argparse
import datetime
import difflib
import json
import os
import re
import shlex
import subprocess
import sys
import textwrap
from contextlib import suppress
from gettext import GNUTranslations
from pathlib import Path

import pygit2

REPO_ROOTDIR = os.path.dirname(os.path.realpath(sys.argv[0]))
REPO_ROOTDIR = os.path.relpath(REPO_ROOTDIR)
SRC_DIR = os.path.join(REPO_ROOTDIR, "gitfourchette")
ASSETS_DIR = os.path.join(SRC_DIR, "assets")
LANG_DIR = os.path.join(ASSETS_DIR, "lang")
LANG_TEMPLATE = os.path.join(LANG_DIR, "gitfourchette.pot")

FORCE = False
LANG_FILTER = "*"

# Language .mo files are not included if the .po file is below this completion percentage.
LANG_MIN_PERCENT_COMPLETE = 5

# Status icons generated by generateIcons(): delta status -> (glyph, tile color).
# Colored on purpose: scanning a long file list, the hue is what the eye picks
# up first, the glyph confirms it. Mid-tone colors, so a white glyph reads on
# every tile and every tile reads on light and dark themes alike.
STATUS_ICONS = {
    "A": ("A", "#1a7f37"),  # added: green
    "D": ("D", "#cf222e"),  # deleted: red
    "M": ("M", "#b76e00"),  # modified: amber
    "R": ("R", "#8250df"),  # renamed: purple
    "T": ("T", "#0a7e8c"),  # typechange: teal
    "U": ("?", "#bc4c00"),  # unmerged: burnt orange
    "X": ("X", "#6e7781"),  # unknown: gray
}

WEBLATE_LANGUAGES = {
    "Chinese (Simplified Han script)": "zh_Hans",
    "Chinese (Traditional Han script)": "zh_Hant",
    "Czech": "cs",
    "French": "fr",
    "German": "de",
    "Italian": "it",
    "Korean": "ko",
    "Portuguese (Brazil)": "pt_BR",
    "Portuguese": "pt",
    "Russian": "ru",
    "Spanish": "es",
    "Turkish": "tr",
    "Ukrainian": "uk",
}


def makeParser():
    parser = argparse.ArgumentParser(description="Update GitFourchette assets")

    parser.add_argument("-f", "--force", action="store_true",
                        help="skip mtime and equality checks before regenerating an asset")

    parser.add_argument("-V", "--version", action="store_true",
                        help="show tool versions and exit")

    loc_group = parser.add_argument_group("Localization options")

    loc_group.add_argument("--pot", action="store_true",
                           help="sync .pot template with new strings from python code")

    loc_group.add_argument("--po", action="store_true",
                           help="sync translatable .po files with .pot template")

    loc_group.add_argument("--mo", action="store_true",
                           help="compile .po files to .mo so you can try them in GitFourchette")

    loc_group.add_argument("--lang",
                           type=str, nargs='?', const=LANG_FILTER,
                           metavar="LANGCODE",
                           help="Sync .pot/.po/.mo files (run all localization steps above). "
                                "Pass 2-letter code to sync a single language, or omit to sync all.")

    loc_group.add_argument("--clean-po", action="store_true",
                           help="remove obsolete strings from .po files")

    ui_group = parser.add_argument_group("UI Designer options")

    ui_group.add_argument("-u", "--ui", action="store_true",
                          help="update ui_*.py files from .ui files (and svg status icons)")

    ui_group.add_argument("--uic", default="pyuic6",
                          help="path to Python-compatible uic tool ('pyuic6' by default; AVOID 'pyside6-uic' because its output doesn't work with PyQt6)")

    ui_group.add_argument("--no-uic-cleanup", action="store_true",
                          help="don't postprocess uic output")

    pkg_group = parser.add_argument_group("Packaging options")

    pkg_group.add_argument("--freeze", default="", metavar="QT_API",
                           help="write frozen constants to appconsts.py and exit")

    credits_group = parser.add_argument_group("Credits options")

    credits_group.add_argument("--contributors", action="store_true",
                           help="format code contributor list")

    credits_group.add_argument("--weblate-credits", default="", metavar="JSON_REPORT",
                           help="format translator credits from Weblate JSON report (https://hosted.weblate.org/projects/gitfourchette/gitfourchette/#reports)")

    return parser


def call(*args, **kwargs) -> subprocess.CompletedProcess:
    print(f"> {shlex.join(args)}")
    capture_output = kwargs.pop("capture_output", True)
    check = kwargs.pop("check", True)
    try:
        return subprocess.run(args, encoding='utf-8', capture_output=capture_output, check=check, **kwargs)
    except subprocess.CalledProcessError as e:
        print(f"Aborting: {e}")
        sys.exit(1)


def writeIfDifferent(path: Path, text: str, ignoreChangedLines=None):
    ignoreChangedLines = ignoreChangedLines or []
    needRewrite = True

    if not FORCE and path.is_file():
        ignoreList = []
        for icl in ignoreChangedLines:
            ignoreList.append("+ " + icl)
            ignoreList.append("- " + icl)

        # See if the differences can be ignored (e.g. Qt User Interface Compiler version comment)
        oldText = path.read_text(encoding="utf-8")
        needRewrite = False
        if oldText != text:
            t1 = oldText.splitlines(keepends=True)
            t2 = text.splitlines(keepends=True)
            for dl in difflib.ndiff(t1, t2):
                if (dl.rstrip() not in ["+", "-"]  # pure whitespace change
                        and not dl.startswith(tuple(ignoreList))
                        and dl.startswith(("+ ", "- "))):
                    needRewrite = True
                    break

    if needRewrite:
        path.write_text(text, encoding="utf-8")
        print("Wrote", path)
    else:
        path.touch()


def patchSection(path: Path, contents: str):
    def ensureNewline(s: str):
        return s + ("" if s.endswith("\n") else "\n")

    text = path.read_text(encoding="utf-8")
    contents = ensureNewline(contents)
    lines = contents.splitlines(keepends=True)
    assert len(lines) >= 2
    beginMarker = lines[0]
    endMarker = lines[-1]
    assert beginMarker
    assert endMarker

    beginPos = text.index(beginMarker)
    endPos = text.index(endMarker.rstrip())

    newText = (text[: beginPos] + contents + text[endPos + len(endMarker) :])
    writeIfDifferent(path, newText)
    return newText


def statusIconSvg(glyph: str, color: str) -> str:
    # A filled tile with a white glyph. No 'gray' recolor token and no dark
    # variant: the tile brings its own background, so it looks the same on
    # any theme (see _autoDarkVariants in iconbank.py).
    return "\n".join([
        "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'>",
        f"<rect rx='2' x='1' y='1' width='14' height='14' fill='{color}'/>",
        f"<text x='8' y='12' font-weight='bold' font-size='11' font-family='sans-serif' text-anchor='middle' fill='white'>{glyph}</text>",
        "</svg>",
        "",
    ])


def writeStatusIcon(status: str, glyph: str, color: str):
    svgPath = Path(ASSETS_DIR) / f"icons/status_{status.lower()}.svg"
    writeIfDifferent(svgPath, statusIconSvg(glyph, color))


def compileUi(uic: str, uiPath: Path, pyPath: Path, force=False, cleanupOutput=True):
    if not force:
        with suppress(FileNotFoundError):
            if pyPath.stat().st_mtime > uiPath.stat().st_mtime:
                return

    result = call(uic, uiPath.name, cwd=uiPath.parent)
    text = result.stdout
    nukePatterns = []
    ignoreDiffs = []

    myImport = "from gitfourchette.localization import *\nfrom gitfourchette.qt import *"

    if not cleanupOutput:
        pass

    elif "from PyQt" in text:
        # Clean up pyuic6 output (pyqt6, generated code is compatible with pyside6 too)
        text = re.sub(r"^from PyQt[56] import .+$", myImport, text, count=1, flags=re.MULTILINE)
        text = re.sub(r"_translate(?=\(\")", "_p", text, flags=re.MULTILINE)

        nukePatterns = [
            # No need to spell out Qt module names with gitfourchette.qt
            r"(?<!\w)Qt(Core|Gui|Widgets)\.",

            # We substituted _translate calls above already
            r"^\s+_translate = QCoreApplication\.translate\n",

            # QMetaObject.connectSlotsByName may cause PyQt to hang if running
            # under pytest-cov. GitFourchette doesn't need this feature anyway:
            # https://riverbankcomputing.com/static/Docs/PyQt6/signals_slots.html#connecting-slots-by-name
            r"^\s+QMetaObject\.connectSlotsByName\(.+\)\n",

            # mypy is smart enough for these now
            r"\s+# type: ignore$",
        ]

        ignoreDiffs = ["# Created by: PyQt6 UI code generator"]
        text = text.strip() + "\n"

    elif "from PySide" in text:
        # WARNING: pyside6-uic cleanup provided here for convenience,
        # but note that the generated code incompatible with pyqt6!
        text = re.sub(r"^from PySide6.* import \([^\)]+\)$", myImport, text, count=1, flags=re.MULTILINE)
        text = re.sub(r"QCoreApplication\.translate\((.+), None\)", r"_p(\1)", text, flags=re.MULTILINE)
        nukePatterns = [
            r"^#if QT_CONFIG\(.+\n",
            r"^#endif // QT_CONFIG\(.+\n",
            r"^from PySide6.* import \([^\)]+\)$\n",
            r"^ {4}# (setupUi|retranslateUi)$\n",
            r"^\s+QMetaObject\.connectSlotsByName\(.+\)\n",
        ]
        ignoreDiffs = ["## Created by: Qt User Interface Compiler version"]
        text = text.strip() + "\n"

    else:
        print("Unknown uic output")

    for pattern in nukePatterns:
        text = re.sub(pattern, "", text, flags=re.MULTILINE)

    writeIfDifferent(pyPath, text, ignoreDiffs)


def compileUiFiles(uic, force, cleanupOutput):
    for uiPath in Path(SRC_DIR).glob("**/*.ui"):
        pyPath = uiPath.parent / f"ui_{uiPath.stem}.py"
        compileUi(uic, uiPath, pyPath, force=force, cleanupOutput=cleanupOutput)

    for pyPath in Path(SRC_DIR).glob("**/ui_*.py"):
        uiPath = pyPath.parent / (pyPath.stem.removeprefix("ui_") + ".ui")
        if not uiPath.exists():
            print("[!] Removing obsolete compiled ui file because there's no matching designer file:", pyPath)
            pyPath.unlink()


def generateIcons():
    # Generate status icons.
    # 'C' (copied) doesn't appear in GitFourchette.
    for status, (glyph, color) in STATUS_ICONS.items():
        writeStatusIcon(status, glyph, color)


def updatePotTemplate():
    """ Update .pot files from strings contained in the source code """
    # Gather all .py files
    pyFiles = [str(f.relative_to(SRC_DIR)) for f in Path(SRC_DIR).glob("**/*.py")]
    pyFiles.sort()
    call(
        "xgettext",
        "--output=" + LANG_TEMPLATE,
        "--sort-by-file",
        "--no-wrap",
        "--language=Python",
        "--from-code=UTF-8",
        "--keyword=_n:1,2",
        "--keyword=_p:1c,2",
        "--keyword=_np:1c,2,3",
        "--directory=" + SRC_DIR,
        "--package-name=GitFourchette",
        "--msgid-bugs-address=https://github.com/jorio/gitfourchette/issues",
        *pyFiles,
        capture_output=False,
    )

    nukePatterns = [
        r"^# SOME DESCRIPTIVE TITLE\.\n",
        r"^# Copyright .C. YEAR THE PACKAGE'S COPYRIGHT HOLDER\n",
        r"^# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR\.\n",
        r'^"POT-Creation-Date: .+"\n',
        r'^"PO-Revision-Date: .+"\n',
        r'^"Language-Team: .+"\n',
    ]
    text = Path(LANG_TEMPLATE).read_text(encoding="utf-8")
    for pattern in nukePatterns:
        text = re.sub(pattern, "", text, flags=re.MULTILINE)
    Path(LANG_TEMPLATE).write_text(text, "utf-8")


def listPoFiles():
    for poPath in Path(LANG_DIR).glob("*.po"):
        if LANG_FILTER == "*" or poPath.stem == LANG_FILTER:
            yield poPath


def updatePoFiles():
    """ Update .po files from strings contained in the .pot template """
    for poPath in listPoFiles():
        call(
            "msgmerge",
            "--update",
            "--sort-by-file",
            "--no-wrap",
            "--backup=off",
            str(poPath),
            LANG_TEMPLATE,
            capture_output=False)


def cleanUpPoFiles():
    """ Remove obsolete strings from .po files """
    for poPath in listPoFiles():
        call(
            "msgattrib",
            "--sort-by-file",
            "--no-wrap",
            "--no-obsolete",
            "-o", str(poPath),
            str(poPath),
            capture_output=False)


def compileMoFiles():
    """ Generate .mo files from .po files """
    wipLanguages = []

    def extractStderrNumber(pattern, stderr):
        match = re.search(pattern, stderr)
        return int(match.group(1)) if match else 0

    for poPath in listPoFiles():
        moPath = poPath.with_suffix(".mo")
        moBackupPath = moPath.with_suffix(".mo.bak")

        oldCatalog: dict = {}
        with suppress(FileNotFoundError), open(moPath, "rb") as fp:
            oldCatalog = GNUTranslations(fp)._catalog
            moPath.rename(moBackupPath)

        msgfmt = call("msgfmt", "--no-hash", "--statistics", "-o", str(moPath), str(poPath),
                      env={"LANGUAGE": "C"}, capture_output=True)

        complete = extractStderrNumber(r"(\d+) translated messages", msgfmt.stderr)
        missing1 = extractStderrNumber(r"(\d+) fuzzy translations", msgfmt.stderr)
        missing2 = extractStderrNumber(r"(\d+) untranslated messages", msgfmt.stderr)
        ratio = round(100.0 * complete / (complete + missing1 + missing2))
        print(f"  {poPath.stem}: {ratio}% complete | {msgfmt.stderr.strip()}")

        wipLanguages.append(f"{moPath.stem} {ratio}")

        try:
            # Remove nearly-empty mo files
            if ratio <= LANG_MIN_PERCENT_COMPLETE:
                print(f"*** Removing empty translation '{poPath.name}'")
                moPath.unlink()
                continue

            # If none of the strings changed, keep old .mo file
            if oldCatalog:
                with open(moPath, "rb") as fp:
                    newCatalog: dict = GNUTranslations(fp)._catalog

                if all(oldCatalog.get(k, None) == newCatalog[k] for k in newCatalog):
                    print(f"*** {poPath.name} unchanged, keeping old {moPath.name}")
                    moPath.unlink()
                    moBackupPath.rename(moPath)
        finally:
            moBackupPath.unlink(missing_ok=True)

    wipLanguages.sort()
    Path(LANG_DIR, "wip.txt").write_text("\n".join(wipLanguages) + "\n")


def formatTranslatorCredits(jsonReportPath: str):
    blob = Path(jsonReportPath).read_bytes()
    originalTable = json.loads(blob)

    table = {}
    contribs = {}

    for entry in originalTable:
        for language, people in entry.items():
            languageCode = WEBLATE_LANGUAGES[language]
            if languageCode == "fr":
                continue
            table[languageCode] = [p["full_name"] for p in people if p["username"] != "jorio"]
            contribs[languageCode] = sum(p["change_count"] for p in people)

    # Keep what Weblate doesn't know about: languages translated elsewhere, and
    # translators given a link or a country by hand (they replace their plain name)
    creditsPath = Path(LANG_DIR, "credits.json")
    with suppress(FileNotFoundError):
        for languageCode, people in json.loads(creditsPath.read_text("utf-8")).items():
            if languageCode not in table:
                table[languageCode] = people
                contribs[languageCode] = 0
                continue
            for person in people:
                if not isinstance(person, dict):
                    continue
                names = table[languageCode]
                if person["name"] in names:
                    names[names.index(person["name"])] = person
                else:
                    names.append(person)

    sortedKeys = sorted(table.keys(), key=lambda k: contribs[k], reverse=True)
    table = {k: table[k] for k in sortedKeys}

    creditsPath.write_text(json.dumps(table, indent="\t") + "\n")


def formatContributors():
    process = call("git", "shortlog", "--summary", "--numbered", ":!gitfourchette/assets/lang")

    contributors = [
        line.split("\t", 1)[1]
        for line in process.stdout.splitlines(keepends=True)
    ]

    Path(ASSETS_DIR, "contributors.txt").write_text("".join(contributors))


def writeFreezeFile(qtApi: str):
    repo = pygit2.Repository(SRC_DIR)
    headCommit = repo.head.target

    buildDate = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d %H:%M")
    freezeText = textwrap.dedent(f"""\
        # BEGIN_FREEZE_CONSTS
        ####################################
        # Do not commit these changes!
        ####################################

        APP_FREEZE_COMMIT = "{headCommit}"
        APP_FREEZE_DATE = "{buildDate}"
        APP_FREEZE_QT = "{qtApi.lower()}"
        # END_FREEZE_CONSTS""")
    patchSection(Path(SRC_DIR) / 'appconsts.py', freezeText)


if __name__ == '__main__':
    args = makeParser().parse_args()

    FORCE = args.force

    if args.lang:
        args.pot = True
        args.po = True
        args.mo = True
        LANG_FILTER = args.lang

    if args.version:
        toolVersions = ""
        toolVersions += args.uic + " " + call(args.uic, "--version").stdout
        toolVersions += call("msgmerge", "--version").stdout.splitlines()[0]
        print(toolVersions)
        sys.exit(0)

    if args.freeze:
        writeFreezeFile(args.freeze)
        sys.exit(0)

    if not (args.ui or args.pot or args.po or args.mo or args.clean_po or args.weblate_credits or args.contributors):
        makeParser().print_usage()
        sys.exit(1)

    # Generate .py files from .ui files
    if args.ui:
        generateIcons()
        compileUiFiles(args.uic, args.force, not args.no_uic_cleanup)

    if args.pot:
        updatePotTemplate()

    if args.po:
        updatePoFiles()

    if args.mo:
        compileMoFiles()

    if args.clean_po:
        cleanUpPoFiles()

    if args.weblate_credits:
        formatTranslatorCredits(args.weblate_credits)

    if args.contributors:
        formatContributors()
