# Form implementation generated from reading ui file 'workspacedialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from gitfourchette.localization import *
from gitfourchette.qt import *


class Ui_WorkspaceDialog(object):
    def setupUi(self, WorkspaceDialog):
        WorkspaceDialog.setObjectName("WorkspaceDialog")
        WorkspaceDialog.resize(520, 460)
        WorkspaceDialog.setSizeGripEnabled(True)
        WorkspaceDialog.setModal(True)
        self.verticalLayout = QVBoxLayout(WorkspaceDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameLayout = QHBoxLayout()
        self.nameLayout.setObjectName("nameLayout")
        self.nameLabel = QLabel(parent=WorkspaceDialog)
        self.nameLabel.setObjectName("nameLabel")
        self.nameLayout.addWidget(self.nameLabel)
        self.nameEdit = QLineEdit(parent=WorkspaceDialog)
        self.nameEdit.setObjectName("nameEdit")
        self.nameLayout.addWidget(self.nameEdit)
        self.verticalLayout.addLayout(self.nameLayout)
        self.reposHeaderLayout = QHBoxLayout()
        self.reposHeaderLayout.setObjectName("reposHeaderLayout")
        self.reposLabel = QLabel(parent=WorkspaceDialog)
        self.reposLabel.setObjectName("reposLabel")
        self.reposHeaderLayout.addWidget(self.reposLabel)
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.reposHeaderLayout.addItem(spacerItem)
        self.selectAllButton = QPushButton(parent=WorkspaceDialog)
        self.selectAllButton.setAutoDefault(False)
        self.selectAllButton.setObjectName("selectAllButton")
        self.reposHeaderLayout.addWidget(self.selectAllButton)
        self.deselectAllButton = QPushButton(parent=WorkspaceDialog)
        self.deselectAllButton.setAutoDefault(False)
        self.deselectAllButton.setObjectName("deselectAllButton")
        self.reposHeaderLayout.addWidget(self.deselectAllButton)
        self.verticalLayout.addLayout(self.reposHeaderLayout)
        self.filterEdit = QLineEdit(parent=WorkspaceDialog)
        self.filterEdit.setClearButtonEnabled(True)
        self.filterEdit.setObjectName("filterEdit")
        self.verticalLayout.addWidget(self.filterEdit)
        self.repoList = QListWidget(parent=WorkspaceDialog)
        self.repoList.setAlternatingRowColors(True)
        self.repoList.setUniformItemSizes(True)
        self.repoList.setObjectName("repoList")
        self.verticalLayout.addWidget(self.repoList)
        self.footerLayout = QHBoxLayout()
        self.footerLayout.setObjectName("footerLayout")
        self.countLabel = QLabel(parent=WorkspaceDialog)
        self.countLabel.setText("")
        self.countLabel.setObjectName("countLabel")
        self.footerLayout.addWidget(self.countLabel)
        self.buttonBox = QDialogButtonBox(parent=WorkspaceDialog)
        self.buttonBox.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.footerLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.footerLayout)
        self.nameLabel.setBuddy(self.nameEdit)
        self.reposLabel.setBuddy(self.filterEdit)

        self.retranslateUi(WorkspaceDialog)
        self.buttonBox.rejected.connect(WorkspaceDialog.reject)
        self.buttonBox.accepted.connect(WorkspaceDialog.accept)
        WorkspaceDialog.setTabOrder(self.nameEdit, self.filterEdit)
        WorkspaceDialog.setTabOrder(self.filterEdit, self.repoList)
        WorkspaceDialog.setTabOrder(self.repoList, self.selectAllButton)
        WorkspaceDialog.setTabOrder(self.selectAllButton, self.deselectAllButton)

    def retranslateUi(self, WorkspaceDialog):
        WorkspaceDialog.setWindowTitle(_p("WorkspaceDialog", "Workspace"))
        self.nameLabel.setText(_p("WorkspaceDialog", "&Name:"))
        self.reposLabel.setText(_p("WorkspaceDialog", "&Repositories in this workspace:"))
        self.selectAllButton.setText(_p("WorkspaceDialog", "Select &all"))
        self.deselectAllButton.setText(_p("WorkspaceDialog", "&Deselect all"))
        self.filterEdit.setPlaceholderText(_p("WorkspaceDialog", "Type a name to filter…"))
